feat: Add `Guide menu` to on-screen virtual controller
moonlight-stream/moonlight-android pull request #1265
Opened 2023-10-23 01:30 UTC by mattvgm

In some games/applications the `guide menu`(or Xbox button) is actually important, for example when using `Steam Big Picture` this button opens the big picture's menu to tweak controller,exit game, etc...

This PR adds to the On-screen virtual controller the `Guide Menu` (The name can be changed) between the `START` and `BACK` buttons.

It also adds a configuration for the ones that want to hide it and don't need to use it.

Personally this helps me 100% as my second generic gamepad does not have this button and I have other combos mapped to `BACK + START`. I would even add a configuration to only have this button, but I thin the PR #1247 already address it in a good way.

Tested with both #1247 and #1171 and works perfectly

2024-04-08 15:32 UTC, jk7gr commented
I am really looking forward to it as it will be a game changer for those using the app to connect to Batocera OS where the button acts like hotkey for several functionality.

2024-04-11 17:19 UTC, mattvgm commented
@jk7gr I've been using for a while and it works fine for me.

@cgutman When you have time can you please give it a look on this PR, I can improve it further if necessary. Thanks

2024-07-25 16:21 UTC, ReenigneArcher requested changes
@mattvgm I am the maintainer of Sunshine and getting more involved in the Moonlight side. I'm trying to help out by completing some pre-reviews before they go to cgutman.

This seems good to me. I am going to test these changes later, but for now I have a few code style nit picks.

2024-07-25 16:21 UTC, ReenigneArcher commented on app/src/main/java/com/limelight/binding/input/virtual_controller/VirtualControllerConfigurationLoader.java
> +    //Make the Guide Menu be in the center of START and BACK menu
```suggestion
    // Make the Guide Menu be in the center of START and BACK menu
```

nit

2024-07-25 16:21 UTC, ReenigneArcher commented on app/src/main/java/com/limelight/binding/input/virtual_controller/VirtualControllerConfigurationLoader.java
> +
```suggestion
```

remove extra line that was added

2024-07-25 16:21 UTC, ReenigneArcher commented on app/src/main/java/com/limelight/binding/input/virtual_controller/VirtualControllerConfigurationLoader.java
> +
```suggestion
```

remove extra line

2024-07-27 19:45 UTC, ReenigneArcher approved these changes
I tested the changes and everything works as expected.

I do have one question, since I am new to this codebase, which is regarding the translations. https://github.com/moonlight-stream/moonlight-android/pull/1314#discussion_r1691817532

2024-07-27 21:21 UTC, merged