Add support for two finger scroll and right click with trackpad
moonlight-stream/moonlight-android pull request #1386
Opened 2024-07-10 04:12 UTC by ClassicOldSong

Resolves https://github.com/moonlight-stream/moonlight-android/issues/1383

2024-07-10 20:59 UTC, ClassicOldSong commented
Download build at https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-BLACK

2024-07-25 15:03 UTC, ReenigneArcher requested changes
I think some of the if/else nesting can be improved.

2024-07-25 16:07 UTC, ClassicOldSong commented on app/src/main/java/com/limelight/binding/input/touch/TrackpadContext.java
> +            }
The multi-finger implementation originally written is pertty hard to maintain. It has multiple states that can only be handled like this.

It's better if the multi-finger handler could be refactored completely.

2024-07-25 16:07 UTC, ClassicOldSong commented on app/src/main/java/com/limelight/binding/input/touch/TrackpadContext.java
> +        }
Code style and syntax goes last.

2024-07-25 16:09 UTC, ClassicOldSong commented on app/src/main/java/com/limelight/Game.java
> +                    }
For clearity issue, I prefer nested `if` in the `else`.

2024-07-25 16:10 UTC, ClassicOldSong commented on app/src/main/java/com/limelight/binding/input/touch/TrackpadContext.java
> +        }
https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/binding/input/touch/RelativeTouchContext.java#L138-L146

2024-07-26 07:16 UTC, ClassicOldSong commented
Closing this PR since it's actually helping people out.

What a drama in the discord server!

Getting kicked for helping people out when the main project has no updates and no message about updates for months, get slammed by "you fixed the issue you opened doesn't necessarily mean others have the same issue", "you fixed your problem but might break every else" and "Either be patient or go away".

Sure, I'll go away, no more PRs to help people actually in need and I still wish good luck to you.

2024-07-26 07:16 UTC, closed without merging